### ISSUE TITLE
IP issues of AdvisorAnnotate.cs and advisor_annotate.f90

### ISSUE THREAD

**Issue by robertlinux** [intel/ittapi#149]
The ittapi's license is GPL-2.0-only and BSD-3-Clause, but the following two files have extra statement:

include/AdvisorAnnotate.cs
include/fortran/advisor_annotate.f90

"""
// SAMPLE SOURCE CODE - SUBJECT TO THE TERMS OF END-USER LICENSE AGREEMENT
// FOR INTEL(R) ADVISOR XE 2018.
"""
Does the above statement conflict with  GPL-2.0-only and BSD-3-Clause? Can ittapi's user build and release the above two files as FOSS code, please?

**Comment by eparshut** [comment]
@robertlinux, thanks for the reported issue. It looks like we just forgot to update the copyright in these source files. Now it fixed
