### ISSUE TITLE
buildall.py requires 32bit compatibility layer

### ISSUE THREAD

**Issue by nagorny** [intel/ittapi#8]
buildall.py requires 32bit compatibility layer but there is no information about this dependency. 
The same time buildall.py has code:
```python
    target_bits = ['64']
    if (sys.platform != 'darwin'):  # on MAC OSX we produce FAT library including both 32 and 64 bits
        target_bits.append('32')

    print("target_bits", target_bits)
```

suggesting that it should be somehow configured. I didn't find how to disable 32bit build. It seems to be an error.

**Comment by ekovanova** [comment]
@nagorny good catch, I've added --force_bits option to specify a bit version
