### ISSUE TITLE
Add Security Policy

### ISSUE THREAD

**Issue by rahulchaphalkar** [intel/ittapi#95]
Adding a security policy (`security.md`) for vulnerability reporting is generally a good practice, and projects like Envoy [have this as a requirement](https://github.com/intel/ittapi/blob/master/LICENSES/BSD-3-Clause.txt) for adding external dependencies.
If there are no objections, I can add a barebones one. Is there any point of contact for such vulnerabilities? 
Otherwise, if any maintainer can configuring [private vulnerability reporting](https://docs.github.com/en/code-security/security-advisories/repository-security-advisories/configuring-private-vulnerability-reporting-for-a-repository#configuring-notifications-for-private-vulnerability-reporting), that would work as well. The security policy needs to have [one of the above options](https://docs.github.com/en/code-security/security-advisories/guidance-on-reporting-and-writing/about-coordinated-disclosure-of-security-vulnerabilities#about-reporting-and-disclosing-vulnerabilities-in-projects-on-github).

**Comment by rahulchaphalkar** [comment]
Opened a PR https://github.com/intel/ittapi/pull/97

**Comment by abrown** [comment]
Resolved in #97.
